services:
  frontend:
    build: .
    container_name: tp-frontend-standalone
    ports:
      - "80002:80002"
    environment:
      API_BASE_INTERNAL: ${API_BASE_INTERNAL:-http://localhost:80001}
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://localhost:80001}
    restart: unless-stopped
