INSERT INTO app.interview_questions (id, text, category, difficulty, answer_tips, star_cues, evaluation_criteria, sample_answer, is_active) VALUES
-- Leadership
(gen_random_uuid(), 'Tell me about a time you had to lead a team through a difficult project deadline.', 'leadership', 'medium', 'Focus on how you motivated the team and managed priorities.', '{"situation": "Team facing tight deadline", "task": "Deliver project on time", "action": "Prioritized tasks and motivated team", "result": "Delivered on time with quality"}', ARRAY['Clear communication of vision', 'Delegation effectiveness', 'Handling team morale', 'Decision-making under pressure'], 'In my previous role, our team had 2 weeks to deliver a critical feature...', true),
(gen_random_uuid(), 'Describe a situation where you had to make an unpopular decision as a leader.', 'leadership', 'hard', 'Explain your reasoning and how you handled pushback.', '{"situation": "Budget cuts required team restructuring", "task": "Reorganize team while maintaining morale", "action": "Transparent communication and fair process", "result": "Team accepted and productivity maintained"}', ARRAY['Transparency in communication', 'Stakeholder management', 'Ethical decision-making', 'Handling resistance'], 'When our company faced budget constraints...', true),
(gen_random_uuid(), 'How have you developed leadership skills in junior team members?', 'leadership', 'medium', 'Show mentorship approach with concrete examples.', '{"situation": "Junior developers lacking confidence", "task": "Build their technical leadership", "action": "Pair programming and gradual ownership", "result": "Two juniors became tech leads"}', ARRAY['Mentorship approach', 'Creating growth opportunities', 'Feedback delivery', 'Measuring development'], 'I believe in growing leaders from within...', true),

-- Teamwork
(gen_random_uuid(), 'Tell me about a time you worked with a difficult team member.', 'teamwork', 'medium', 'Focus on empathy and constructive resolution.', '{"situation": "Team member not meeting deadlines", "task": "Maintain team velocity", "action": "Private conversation to understand root cause", "result": "Improved collaboration and on-time delivery"}', ARRAY['Empathy and active listening', 'Conflict resolution approach', 'Professionalism', 'Outcome focus'], 'I once worked with a senior developer who consistently missed code review deadlines...', true),
(gen_random_uuid(), 'Describe a time when you helped resolve a conflict between team members.', 'teamwork', 'hard', 'Show mediation skills and neutrality.', '{"situation": "Two engineers disagreed on architecture", "task": "Resolve impasse blocking the sprint", "action": "Facilitated structured discussion with pros and cons", "result": "Hybrid solution that satisfied both"}', ARRAY['Mediation technique', 'Neutrality', 'Finding win-win', 'Team cohesion'], 'During a microservices migration project...', true),

-- Problem Solving
(gen_random_uuid(), 'Describe a complex technical problem you solved recently.', 'problem_solving', 'hard', 'Walk through your analytical approach step by step.', '{"situation": "Production system experiencing intermittent failures", "task": "Identify and fix root cause", "action": "Systematic debugging with logs and metrics", "result": "Found memory leak, fixed and deployed within 4 hours"}', ARRAY['Analytical thinking', 'Technical depth', 'Methodical approach', 'Learning from the issue'], 'Our production API started returning 500 errors randomly...', true),
(gen_random_uuid(), 'Tell me about a time you had to learn a new technology quickly to solve a problem.', 'problem_solving', 'medium', 'Show learning agility and resourcefulness.', '{"situation": "Project required Kubernetes which team had no experience with", "task": "Deploy application in 1 week", "action": "Intensive self-study and built PoC", "result": "Successful deployment, became team K8s expert"}', ARRAY['Learning speed', 'Resource utilization', 'Practical application', 'Knowledge sharing'], 'When our team was asked to containerize our application...', true),

-- Communication
(gen_random_uuid(), 'How do you explain complex technical concepts to non-technical stakeholders?', 'communication', 'medium', 'Use the STAR method to show a specific example.', '{"situation": "Need to explain ML model to business team", "task": "Get buy-in for AI project budget", "action": "Used analogies and visual demos", "result": "Approved budget of 500M VND"}', ARRAY['Audience awareness', 'Use of analogies', 'Visual communication', 'Checking understanding'], 'I always tailor my communication to the audience...', true),
(gen_random_uuid(), 'Tell me about a time your written documentation prevented a major issue.', 'communication', 'easy', 'Highlight clarity and thoroughness.', '{"situation": "New team members onboarding", "task": "Ensure smooth knowledge transfer", "action": "Created comprehensive runbooks and architecture docs", "result": "Reduced onboarding time from 3 weeks to 1 week"}', ARRAY['Documentation quality', 'Proactive communication', 'Impact measurement', 'Sustainability'], 'In my previous role, I noticed our team had no proper documentation...', true),

-- Adaptability
(gen_random_uuid(), 'Describe a time when project requirements changed significantly mid-way.', 'adaptability', 'medium', 'Show flexibility and positive attitude.', '{"situation": "Client changed requirements after 2 sprints", "task": "Pivot without losing progress", "action": "Refactored architecture to be more modular", "result": "Delivered new requirements on time"}', ARRAY['Flexibility', 'Positive attitude', 'Technical pivoting', 'Stakeholder management'], 'We were building an e-commerce platform when the client decided to pivot to a marketplace model...', true),

-- Conflict Resolution
(gen_random_uuid(), 'Tell me about a time you disagreed with your managers decision.', 'conflict_resolution', 'hard', 'Show respectful disagreement and professionalism.', '{"situation": "Manager wanted to skip testing phase", "task": "Ensure quality without damaging relationship", "action": "Presented data on cost of bugs vs testing time", "result": "Agreed to compressed but thorough testing"}', ARRAY['Respectful communication', 'Data-driven argument', 'Compromise', 'Professional maturity'], 'My manager once asked us to skip integration testing to meet a deadline...', true),

-- Time Management
(gen_random_uuid(), 'How do you prioritize tasks when everything seems urgent?', 'time_management', 'medium', 'Show systematic prioritization framework.', '{"situation": "Multiple critical bugs and feature deadline same week", "task": "Deliver features and fix bugs", "action": "Impact/effort matrix with stakeholders", "result": "Delivered high-impact items on time"}', ARRAY['Prioritization framework', 'Stakeholder alignment', 'Saying no effectively', 'Delivering under pressure'], 'I use an impact vs urgency matrix to prioritize...', true)
-- Fix: evaluation_criteria is JSONB, not text array
-- Replacing ARRAY[...] with JSONB arrays
ON CONFLICT DO NOTHING;

-- Delete the failed inserts first (none should have gone in due to error)
-- Now re-insert with correct types

DELETE FROM app.interview_questions WHERE 1=1;

INSERT INTO app.interview_questions (id, text, category, difficulty, answer_tips, star_cues, evaluation_criteria, sample_answer, is_active) VALUES
(gen_random_uuid(), 'Tell me about a time you had to lead a team through a difficult project deadline.', 'leadership', 'medium', 'Focus on how you motivated the team and managed priorities.', '{"situation": "Team facing tight deadline", "task": "Deliver project on time", "action": "Prioritized tasks and motivated team", "result": "Delivered on time with quality"}', '["Clear communication of vision", "Delegation effectiveness", "Handling team morale", "Decision-making under pressure"]', 'In my previous role, our team had 2 weeks to deliver a critical feature...', true),
(gen_random_uuid(), 'Describe a situation where you had to make an unpopular decision as a leader.', 'leadership', 'hard', 'Explain your reasoning and how you handled pushback.', '{"situation": "Budget cuts required team restructuring", "task": "Reorganize team while maintaining morale", "action": "Transparent communication and fair process", "result": "Team accepted and productivity maintained"}', '["Transparency in communication", "Stakeholder management", "Ethical decision-making", "Handling resistance"]', 'When our company faced budget constraints...', true),
(gen_random_uuid(), 'How have you developed leadership skills in junior team members?', 'leadership', 'medium', 'Show mentorship approach with concrete examples.', '{"situation": "Junior developers lacking confidence", "task": "Build their technical leadership", "action": "Pair programming and gradual ownership", "result": "Two juniors became tech leads"}', '["Mentorship approach", "Creating growth opportunities", "Feedback delivery", "Measuring development"]', 'I believe in growing leaders from within...', true),
(gen_random_uuid(), 'Tell me about a time you worked with a difficult team member.', 'teamwork', 'medium', 'Focus on empathy and constructive resolution.', '{"situation": "Team member not meeting deadlines", "task": "Maintain team velocity", "action": "Private conversation to understand root cause", "result": "Improved collaboration and on-time delivery"}', '["Empathy and active listening", "Conflict resolution approach", "Professionalism", "Outcome focus"]', 'I once worked with a senior developer who consistently missed code review deadlines...', true),
(gen_random_uuid(), 'Describe a time when you helped resolve a conflict between team members.', 'teamwork', 'hard', 'Show mediation skills and neutrality.', '{"situation": "Two engineers disagreed on architecture", "task": "Resolve impasse blocking the sprint", "action": "Facilitated structured discussion with pros and cons", "result": "Hybrid solution that satisfied both"}', '["Mediation technique", "Neutrality", "Finding win-win", "Team cohesion"]', 'During a microservices migration project...', true),
(gen_random_uuid(), 'Describe a complex technical problem you solved recently.', 'problem_solving', 'hard', 'Walk through your analytical approach step by step.', '{"situation": "Production system experiencing intermittent failures", "task": "Identify and fix root cause", "action": "Systematic debugging with logs and metrics", "result": "Found memory leak, fixed and deployed within 4 hours"}', '["Analytical thinking", "Technical depth", "Methodical approach", "Learning from the issue"]', 'Our production API started returning 500 errors randomly...', true),
(gen_random_uuid(), 'Tell me about a time you had to learn a new technology quickly to solve a problem.', 'problem_solving', 'medium', 'Show learning agility and resourcefulness.', '{"situation": "Project required Kubernetes which team had no experience with", "task": "Deploy application in 1 week", "action": "Intensive self-study and built PoC", "result": "Successful deployment, became team K8s expert"}', '["Learning speed", "Resource utilization", "Practical application", "Knowledge sharing"]', 'When our team was asked to containerize our application...', true),
(gen_random_uuid(), 'How do you explain complex technical concepts to non-technical stakeholders?', 'communication', 'medium', 'Use the STAR method to show a specific example.', '{"situation": "Need to explain ML model to business team", "task": "Get buy-in for AI project budget", "action": "Used analogies and visual demos", "result": "Approved budget of 500M VND"}', '["Audience awareness", "Use of analogies", "Visual communication", "Checking understanding"]', 'I always tailor my communication to the audience...', true),
(gen_random_uuid(), 'Tell me about a time your written documentation prevented a major issue.', 'communication', 'easy', 'Highlight clarity and thoroughness.', '{"situation": "New team members onboarding", "task": "Ensure smooth knowledge transfer", "action": "Created comprehensive runbooks and architecture docs", "result": "Reduced onboarding time from 3 weeks to 1 week"}', '["Documentation quality", "Proactive communication", "Impact measurement", "Sustainability"]', 'In my previous role, I noticed our team had no proper documentation...', true),
(gen_random_uuid(), 'Describe a time when project requirements changed significantly mid-way.', 'adaptability', 'medium', 'Show flexibility and positive attitude.', '{"situation": "Client changed requirements after 2 sprints", "task": "Pivot without losing progress", "action": "Refactored architecture to be more modular", "result": "Delivered new requirements on time"}', '["Flexibility", "Positive attitude", "Technical pivoting", "Stakeholder management"]', 'We were building an e-commerce platform when the client decided to pivot to a marketplace model...', true),
(gen_random_uuid(), 'Tell me about a time you disagreed with your managers decision.', 'conflict_resolution', 'hard', 'Show respectful disagreement and professionalism.', '{"situation": "Manager wanted to skip testing phase", "task": "Ensure quality without damaging relationship", "action": "Presented data on cost of bugs vs testing time", "result": "Agreed to compressed but thorough testing"}', '["Respectful communication", "Data-driven argument", "Compromise", "Professional maturity"]', 'My manager once asked us to skip integration testing to meet a deadline...', true),
(gen_random_uuid(), 'How do you prioritize tasks when everything seems urgent?', 'time_management', 'medium', 'Show systematic prioritization framework.', '{"situation": "Multiple critical bugs and feature deadline same week", "task": "Deliver features and fix bugs", "action": "Impact/effort matrix with stakeholders", "result": "Delivered high-impact items on time"}', '["Prioritization framework", "Stakeholder alignment", "Saying no effectively", "Delivering under pressure"]', 'I use an impact vs urgency matrix to prioritize...', true);
